modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/whimsicalwren/Typewriter/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/whimsicalwren/Typewriter"
#logoFile="examplemod.png"
authors="wren"
description='''
A mod to make registries simple, easy, and straightforward.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version}]"
    ordering="NONE"
    side="BOTH"